### ISSUE TITLE
splitting entities

### ISSUE THREAD

**Issue by stevenfletcher125** [gazoodle/gecko-home-assistant#47]
Hello there gazoodle
Great work on this project if only they all worked this well!
I am hoping you can add entities for
-current temp
-current operation mode
-switch operation mode
I know these can be accssed by lovelace but alas I have a seperate TFT sceen with only minimal interface options
many thanks

**Comment by gazoodle** [comment]
Just so I understand:

Current Temp = The actual temperature of the water in the tub (as opposed to the user setpoint in the UI, or indeed the real setpoint after taking eco mode into account)
Current Operation = Cooling/Heating

I'm not sure what you mean by switch operation mode.

**Comment by stevenfletcher125** [comment]
my apologies poor posting on my part

-current temp of the water in the tub
-each of the settings i.e standard, weekender, etc
-turn heating up/down

**Comment by gazoodle** [comment]
I'm pretty sure you can access all the parameters you want from the climate entity that the integration provides for the spa

If you use the developer tools, type in the name of your spa, select the climate entry, you can see all that data

```YAML
hvac_modes:
  - auto
min_temp: 15
max_temp: 40
preset_modes:
  - Away From Home
  - Standard
  - Energy Saving
  - Super Energy Saving
  - Weekender
current_temperature: 32
temperature: 32
hvac_action: idle
preset_mode: Standard
icon: mdi:hot-tub
friendly_name: 'Spa: Heater'
supported_features: 17
```

You can use an automation to change any of the attribute values, you can use the {template} engine to extract just a specific value from the attributes.

How are you driving your TFT screen?
