### ISSUE TITLE
I find the project very useful, please could you add the ability to control spa temperature from an HA Automation

### ISSUE THREAD

**Issue by Harley56** [gazoodle/gecko-home-assistant#73]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gazoodle** [comment]
Use an action of `service` and select `climate.set_temperature`. Then select the spa hvac control and you should be good to go.

The yaml should look something like this …

```yaml
service: climate.set_temperature
data:
  temperature: 15
target:
  device_id: f4ffc72bf…..5d4bf68b

```
